services:
  app:
    volumes:
      - .:/app
    ports:
      - 3000:3000

  caddy:
    volumes:
      - .:/app
      - ./services/caddy/Caddyfile:/etc/caddy/Caddyfile
    ports:
      - 80:80
      - 443:443

  bugsink:
    image: bugsink/bugsink:latest
    ports:
      - 8000:8000
    environment:
      - SECRET_KEY=localdev
      - ALLOWED_HOSTS=localhost,bugsink
      - SUPERUSER_EMAIL=admin@example.com
      - SUPERUSER_PASSWORD=admin
