services:
  app:
    volumes:
      - .:/app
    ports:
      - 3000:3000

  caddy:
    volumes:
      - .:/app
      - ./services/caddy/Caddyfile:/etc/caddy/Caddyfile
    ports:
      - 80:80
      - 443:443

  bugsink:
    image: bugsink/bugsink:latest
    ports:
      - 8000:8000
    environment:
      - SECRET_KEY=localdev-hexlet-devops-example-app-not-for-production-use
      - ALLOWED_HOSTS=localhost,bugsink
      - CREATE_SUPERUSER=admin@example.com:admin
